version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all --noauth # Disable authentication

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true # Activer l'accès admin
      ME_CONFIG_MONGODB_AUTH: false       # Désactiver l'authentification
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  course-service:
    build: ./course-service
    container_name: course-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - course-service
      - payment-service
    environment:
      - JWT_SECRET=secret_key

volumes:
  mongo_data: